version: '3.8'

networks:
  chains:

services:
  otelcol:
    image: otel/opentelemetry-collector:latest
    networks:
      - chains
    volumes:
      - ./collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"

  aa:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - chains
    ports:
      - "3000:3000"
    environment:
      JUMPS: 2
      ID: A
      CHAIN_SVC: http://bb:3000/chain
      COLLECTOR_ENDPOINT: http://otelcol:4318
      ENABLE_METRICS: true
      ENABLE_TRACING: true

  bb:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - chains
    environment:
      JUMPS: 2
      ID: B
      CHAIN_SVC: http://aa:3000/chain
      COLLECTOR_ENDPOINT: http://otelcol:4318
      ENABLE_METRICS: true
      ENABLE_TRACING: true